// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6_5nMid1IxBHpoS4RV1ciKG3aUyY-gCw',
    appId: '1:286842539120:web:92ac7a0e01f0da913cf8b5',
    messagingSenderId: '286842539120',
    projectId: 'stockeaze-fbe5b',
    authDomain: 'stockeaze-fbe5b.firebaseapp.com',
    storageBucket: 'stockeaze-fbe5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmX3_2UXGqEeoCDGy1BUShCbgXReWiqMg',
    appId: '1:286842539120:android:72849c5ae137d92f3cf8b5',
    messagingSenderId: '286842539120',
    projectId: 'stockeaze-fbe5b',
    storageBucket: 'stockeaze-fbe5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY1mOUIgJ7ulONFKlsMrmQB1-7EONuGQE',
    appId: '1:286842539120:ios:b93c14f929ad6ad23cf8b5',
    messagingSenderId: '286842539120',
    projectId: 'stockeaze-fbe5b',
    storageBucket: 'stockeaze-fbe5b.appspot.com',
    iosClientId: '286842539120-ggf0o4kfgqs3e3jpqci16pstclinq0ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY1mOUIgJ7ulONFKlsMrmQB1-7EONuGQE',
    appId: '1:286842539120:ios:b93c14f929ad6ad23cf8b5',
    messagingSenderId: '286842539120',
    projectId: 'stockeaze-fbe5b',
    storageBucket: 'stockeaze-fbe5b.appspot.com',
    iosClientId: '286842539120-ggf0o4kfgqs3e3jpqci16pstclinq0ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFinalProject',
  );
}
